import {helpButton} from './help.js';
import {getCatalog,miniModule,cloneBlock} from './catalog.js';
import {api,json} from './api.js';
import {escape as e,field,textarea,select,modal,toast,errorMessage,badge,kindName,date,icon,bindAsync,publicPath} from './ui.js';
import {openEditor} from './editor.js';
import type {RecordItem,User,Kind,Overview,Inquiry,Media} from './types.js';

function header(eyebrow:string,title:string,description:string,action=''):string {
  return `<div class="page-head"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${description}</p></div>${action}</div>`;
}
function rows(items:RecordItem[],editable=true):string {
  return items.map(item=>`<tr><td><button class="row-title" data-edit="${item.id}"><span class="content-symbol">${icon(item.kind==='page'?'pages':item.kind==='service'?'services':item.kind==='settings'?'settings':'projects')}</span><span><strong>${e(item.data.title)}</strong><small>${e(item.data.slug)}${item.live&&item.state!=='published'?' · Live-Version bleibt aktiv':''}</small></span></button></td><td>${kindName[item.kind]}</td><td>${badge(item.state)}</td><td class="muted">${date(item.updated_at)}</td><td><button class="icon-button" data-edit="${item.id}" aria-label="${e(item.data.title)} ${editable?'bearbeiten':'ansehen'}">↗</button></td></tr>`).join('');
}
function table(items:RecordItem[],editable=true):string {
  return `<div class="table-wrap"><table><thead><tr><th>Inhalt</th><th>Typ</th><th>Status</th><th>Aktualisiert</th><th><span class="sr-only">Aktionen</span></th></tr></thead><tbody>${rows(items,editable)}</tbody></table></div>`;
}
function attachEditors(container:HTMLElement,items:RecordItem[],user:User,refresh:()=>void):void {
  container.querySelectorAll<HTMLButtonElement>('[data-edit]').forEach(button=>bindAsync(button,'click',async()=>{
    const item=items.find(i=>i.id===button.dataset.edit);if(item){const full=await api<RecordItem>('/api/admin/content/'+item.id);await openEditor(full,full.kind,user,refresh);}
  }));
}
export async function overviewView(container:HTMLElement,user:User,refresh:()=>void):Promise<void>{
  const data=await api<Overview>('/api/admin/overview');
  container.innerHTML=header('WORKSPACE / ÜBERSICHT','Dein Studio. Dein System.','Inhalte pflegen, Ideen veröffentlichen und den Überblick behalten.',user.role!=='moderator'?'<div class="action-help"><button class="button primary" id="new-content">＋ Inhalt erstellen</button>'+helpButton('new_content')+'</div>':'')+
    `<div class="workspace-shortcuts"><a class="workspace-shortcut" href="#pages">${icon('pages')}<span><strong>Seite weiterbearbeiten</strong><small>Texte, Module und die Navigation pflegen.</small></span></a><a class="workspace-shortcut" href="#library">${icon('services')}<span><strong>Mit einer Vorlage starten</strong><small>Bausteine entdecken und wiederverwenden.</small></span></a><a class="workspace-shortcut" href="#moderation">${icon('moderation')}<span><strong>Freigaben prüfen</strong><small>${data.pending} Inhalte warten auf eine Entscheidung.</small></span></a></div><div class="welcome-panel"><div><span class="eyebrow">ALLES AN SEINEM PLATZ</span><h2>Ein guter Auftritt.<br>Einfach weitergedacht.</h2><p>Deine Website wächst mit deinen Ideen — nicht mit deiner To-do-Liste.</p><a href="/" target="_blank" rel="noopener">Website ansehen ↗</a></div><div class="dashboard-art" aria-hidden="true"><span></span><span></span><span></span><span></span></div></div>
    <div class="stats-grid"><a href="#pages" class="stat-card"><span>${icon('pages')} Live-Inhalte</span><strong>${data.published}<small>veröffentlicht</small></strong></a><a href="#services" class="stat-card"><span>${icon('services')} Entwürfe</span><strong>${data.drafts}<small>in Bearbeitung</small></strong></a><a href="#moderation" class="stat-card"><span>${icon('moderation')} Zur Prüfung</span><strong>${data.pending}<small>warten auf Freigabe</small></strong></a>${user.role!=='editor'?`<a href="#inbox" class="stat-card"><span>${icon('inbox')} Neue Anfragen</span><strong>${data.new_inquiries}<small>im Studio-Postfach</small></strong></a>`:''}</div>
    <div class="dashboard-columns"><section class="panel"><div class="panel-heading"><h2>Zuletzt bearbeitet</h2><a href="#pages">Alle Inhalte ↗</a></div>${table(data.recent,user.role!=='moderator')}</section><aside class="panel quick-panel"><span class="eyebrow">SO BLEIBT ES EINFACH</span><h2>Dein Redaktionsablauf</h2><div class="workflow-step"><span>01</span><div><strong>Als Entwurf arbeiten</strong><p>Die Live-Website bleibt unverändert.</p></div></div><div class="workflow-step"><span>02</span><div><strong>Zur Prüfung einreichen</strong><p>Inhalte und Vorschau gemeinsam prüfen.</p></div></div><div class="workflow-step"><span>03</span><div><strong>Gezielt veröffentlichen</strong><p>Nur freigegebene Inhalte gehen live.</p></div></div><a class="button" href="#pages">Seitenaufbau öffnen ↗</a></aside></div>
    <div class="workspace-help-banner"><div><span class="eyebrow">NEU IM STUDIO?</span><h2>Eine Frage ist nur einen Klick entfernt.</h2><p>Die blauen Fragezeichen erklären Felder und Funktionen. Im Handbuch findest du komplette Abläufe.</p></div><a class="button" href="#help">Hilfe & Handbuch ↗</a></div><div class="launch-note"><span>${icon('settings')}</span><div><strong>Vor dem Livegang</strong><p>Demo-Marke und Konzeptprojekte ersetzen, Rechtstexte ergänzen, HTTPS und Backups einrichten. Formularanfragen werden gespeichert, aber noch nicht per E-Mail versendet.</p></div></div>`;
  attachEditors(container,data.recent,user,refresh);
  container.querySelector('#new-content')?.addEventListener('click',()=>{
    const dialog=modal(`<header class="modal-header"><div><span class="eyebrow">NEUER INHALT</span><h2>Was möchtest du ergänzen?</h2></div><button class="icon-button" data-close aria-label="Schließen">✕</button></header><div class="create-options"><button data-kind="article">${icon('articles')}<strong>News-Beitrag</strong><span>Journalbeitrag mit Text und flexiblen Modulen</span></button><button data-kind="campaign">${icon('campaigns')}<strong>Kampagne</strong><span>Werbung und Partner zentral pflegen</span></button><button data-kind="service">${icon('services')}<strong>Leistung</strong><span>Neue Expertise als interaktive Kachel</span></button><button data-kind="project">${icon('projects')}<strong>Projekt</strong><span>Eine neue Arbeit für dein Portfolio</span></button><button data-kind="page">${icon('pages')}<strong>Seite</strong><span>Eine Seite aus flexiblen Modulen</span></button></div>`);dialog.className='';dialog.oncancel=null;
    dialog.querySelectorAll<HTMLButtonElement>('[data-kind]').forEach(button=>bindAsync(button,'click',()=>openEditor(null,button.dataset.kind as Kind,user,refresh)));
  });
}
export async function contentView(container:HTMLElement,kind:Kind,user:User,refresh:()=>void):Promise<void>{
 if(kind==='settings'){
  const items=await api<RecordItem[]>('/api/admin/content?kind=settings');
  container.innerHTML=header('WORKSPACE / EINSTELLUNGEN','Deine Marke. Dein Rahmen.','Globale Angaben und Designvarianten an einer Stelle verwalten.',helpButton('settings'))+`<div class="panel settings-summary"><div class="settings-brand">${e(items[0]?.data.brand||'Deine Website')}</div><p>Markenname, Farben, Animationen, Journal und optionale Statistik. Änderungen bleiben bis zur Veröffentlichung im Entwurf.</p><button class="button primary" id="open-settings">Einstellungen bearbeiten ↗</button><div class="notice">Erstellerhinweis: NorphyOG. Der Hinweis liegt außerhalb der CMS-Einstellungen. Keine externen Fonts oder Analyse-Dienste.</div></div>`;
  bindAsync(container.querySelector('#open-settings'),'click',()=>openEditor(items[0],kind,user,refresh));return;
 }
 const titles:Record<string,[string,string]>={page:['Seiten & Module','Bausteine kombinieren. Reihenfolge ändern. Eine Website gestalten.'],service:['Deine Leistungen','Neue Kacheln hinzufügen und Expertise sichtbar machen.'],project:['Deine Arbeiten','Projekte, Bilder und echte Referenzen für dein Portfolio.'],article:['Journal & News','Beiträge schreiben. Mit Modulen gestalten. Bewusst veröffentlichen.'],campaign:['Werbung & Partner','Kampagnen zentral pflegen und in beliebigen Werbeplätzen wiederverwenden.']};
 const [title,description]=titles[kind];
 container.innerHTML=header('INHALTE / '+kindName[kind].toUpperCase(),title,description,`<div class="action-help">${helpButton(kind==='article'?'news':kind==='campaign'?'campaign':'new_content')}${user.role!=='moderator'?`<button class="button primary" id="new-item">＋ ${kindName[kind]} hinzufügen</button>`:''}</div>`)+
 `${kind==='campaign'?'<div class="notice">Veröffentlichung + gültiger Zeitraum + verknüpfter Werbeplatz = sichtbar. Anzeigen werden immer gekennzeichnet. Keine ausführbaren Fremd-Skripte.</div>':''}<div class="list-tools"><label class="search-field"><span aria-hidden="true">⌕</span><input id="content-search" type="search" placeholder="Titel oder URL durchsuchen …" maxlength="80" aria-label="Inhalte durchsuchen"></label><select id="status-filter" aria-label="Nach Status filtern"><option value="">Alle Status</option><option value="published">Veröffentlicht</option><option value="draft">Entwürfe</option><option value="pending">Zur Prüfung</option><option value="rejected">Überarbeiten</option></select><span class="muted" id="result-count"></span></div><div id="content-results"></div><div class="list-pagination"></div>`;
 let offset=0,sequence=0,timer:number|undefined;
 const result=container.querySelector<HTMLElement>('#content-results')!;
 async function render():Promise<void>{
  const tick=++sequence;
  const q=container.querySelector<HTMLInputElement>('#content-search')!.value;
  const state=container.querySelector<HTMLSelectElement>('#status-filter')!.value;
  try{
   const data=await api<{items:RecordItem[];total:number}>('/api/admin/content-index?'+new URLSearchParams({kind,q,state,limit:'24',offset:String(offset)}));
   if(tick!==sequence)return;
   const items=data.items;
   container.querySelector('#result-count')!.textContent=`${data.total} Inhalte`;
   result.innerHTML=items.length?`<div class="content-grid">${items.map(item=>`<article class="content-card"><div class="content-card-visual visual-${e(item.data.art||'page')}"><span class="content-card-letter">${icon(kind==='article'?'articles':kind==='campaign'?'campaigns':kind==='page'?'pages':kind==='project'?'projects':'services')}</span>${badge(item.state)}<span class="card-version">V${item.revision}</span></div><div class="content-card-body"><span class="eyebrow">${kind==='page'||kind==='article'?`${item.block_count||0} MODULE`:e(item.data.category||kindName[kind])}</span><h2>${e(item.data.title)}</h2><p>${e(item.data.description||'Noch keine Kurzbeschreibung.')}</p>${item.note?`<p class="review-note">Rückmeldung: ${e(item.note)}</p>`:''}<div class="content-card-info"><span>${item.live?'● Veröffentlichter Stand':'○ Noch nicht veröffentlicht'}</span><span>Position ${item.data.order}</span></div><div class="content-card-actions"><button class="button" data-edit="${item.id}">${user.role==='moderator'?'Prüfen':'Bearbeiten'} ↗</button><div>${item.live?`<a class="icon-button" href="${e(publicPath(item))}" target="_blank" rel="noopener" aria-label="${kind==='campaign'?'Kampagnenvorschau':'Live-Seite'} öffnen">↗</a>`:''}${user.role!=='moderator'?`<button class="icon-button" data-duplicate="${item.id}" aria-label="${e(item.data.title)} duplizieren">⧉</button>`:''}${user.role==='admin'&&!(kind==='page'&&item.data.slug==='home')?`<button class="icon-button" data-archive="${item.id}" aria-label="${e(item.data.title)} archivieren">×</button>`:''}</div></div></div></article>`).join('')}</div>`:'<div class="panel empty-state"><h2>Raum für deinen nächsten Inhalt.</h2><p>Erstelle einen neuen Eintrag oder passe die Suche an.</p></div>';
   attachEditors(result,items,user,refresh);
   result.querySelectorAll<HTMLButtonElement>('[data-duplicate]').forEach(button=>bindAsync(button,'click',async()=>{
    const source=await api<RecordItem>('/api/admin/content/'+button.dataset.duplicate);
    const clone=structuredClone(source.data);clone.title=(clone.title+' (Kopie)').slice(0,120);clone.slug=clone.slug.slice(0,49)+'-kopie-'+crypto.randomUUID().slice(0,6);
    const created=await api<RecordItem>('/api/admin/content',json('POST',{kind,data:clone}));toast('Kopie als Entwurf angelegt.');refresh();await openEditor(created,kind,user,refresh);
   }));
   result.querySelectorAll<HTMLButtonElement>('[data-archive]').forEach(button=>bindAsync(button,'click',async()=>{
    const item=items.find(i=>i.id===button.dataset.archive)!;
    if(confirm(`„${item.data.title}“ archivieren? Öffentliche Darstellung wird entfernt; Versionen bleiben erhalten.`)){await api(`/api/admin/content/${item.id}/archive`,json('POST',{expected_revision:item.revision}));toast('Inhalt archiviert.');await render();}
   }));
   const pagination=container.querySelector('.list-pagination')!;
   pagination.innerHTML=`<button class="button" type="button" data-prev ${offset===0?'disabled':''}>← Zurück</button><span>Seite ${Math.floor(offset/24)+1} von ${Math.max(1,Math.ceil(data.total/24))} · maximal 24 Karten pro Ansicht</span><button class="button" type="button" data-next ${offset+24>=data.total?'disabled':''}>Weiter →</button>`;
   pagination.querySelector('[data-prev]')!.addEventListener('click',()=>{offset=Math.max(0,offset-24);void render();});pagination.querySelector('[data-next]')!.addEventListener('click',()=>{offset+=24;void render();});
  }catch(err){result.innerHTML=`<div class="notice" role="alert">${e(errorMessage(err))}</div>`;}
 }
 container.querySelector('#content-search')!.addEventListener('input',()=>{clearTimeout(timer);timer=window.setTimeout(()=>{offset=0;void render();},250);});
 container.querySelector('#status-filter')!.addEventListener('change',()=>{offset=0;void render();});
 bindAsync(container.querySelector('#new-item'),'click',()=>openEditor(null,kind,user,refresh));await render();
}
export async function moderationView(container:HTMLElement,user:User,refresh:()=>void,offset=0):Promise<void>{
  const listing=await api<{items:RecordItem[];total:number}>('/api/admin/content-index?state=pending&limit=24&offset='+offset);const items=listing.items;
  const canModerate=user.role==='admin'||user.role==='moderator';
  container.innerHTML=header('REDAKTION / FREIGABEN','Prüfen. Dann veröffentlichen.','Ein klarer Freigabeschritt zwischen einer Idee und der Live-Website.')+
    `<div class="notice">${canModerate?'Prüfe den gespeicherten Entwurf über „Vorschau & Inhalt“. Änderungen an bereits veröffentlichten Inhalten ersetzen den Live-Stand erst nach der Freigabe.':'Deine eingereichten Inhalte warten hier auf eine Freigabe durch Moderation oder Administration.'}</div><div class="queue-heading"><h2>${listing.total} ${listing.total===1?'Inhalt wartet':'Inhalte warten'} auf Prüfung</h2></div>`+
    (items.length?items.map(item=>`<article class="review-card"><div class="review-icon">${icon(item.kind==='page'?'pages':item.kind==='project'?'projects':'services')}</div><div class="review-info"><span class="eyebrow">${kindName[item.kind]} / VERSION ${item.revision}</span><h2>${e(item.data.title)}</h2><p>${e(item.data.description)}</p><span class="muted">${date(item.updated_at)} ${item.live?'· ersetzt eine veröffentlichte Version':'· erstmals veröffentlichen'}</span></div><div class="review-actions"><button class="button" data-edit="${item.id}">Vorschau & Inhalt ↗</button>${canModerate&&(item.kind!=='settings'||user.role==='admin')?`<div><button class="button" data-reject="${item.id}">Zurückgeben</button><button class="button primary" data-approve="${item.id}">Freigeben</button></div>`:''}</div></article>`).join(''):`<div class="panel empty-state"><span class="empty-icon">${icon('moderation')}</span><h2>Alles geprüft.</h2><p>Neue Einreichungen erscheinen automatisch hier, sobald du die Ansicht öffnest.</p><a class="button" href="#pages">Zu den Seiten ↗</a></div>`);
  addPaging(container,offset,24,offset+24<listing.total,n=>void moderationView(container,user,refresh,n));
  attachEditors(container,items,user,refresh);
  container.querySelectorAll<HTMLButtonElement>('[data-approve]').forEach(button=>bindAsync(button,'click',async()=>{
    const item=items.find(i=>i.id===button.dataset.approve)!;
    if(confirm(`„${item.data.title}“ jetzt öffentlich freigeben?`)){await api(`/api/admin/content/${item.id}/publish`,json('POST',{expected_revision:item.revision}));toast('Inhalt veröffentlicht.');refresh();}
  }));
  container.querySelectorAll<HTMLButtonElement>('[data-reject]').forEach(button=>button.addEventListener('click',()=>{
    const item=items.find(i=>i.id===button.dataset.reject)!;
    const dialog=modal(`<header class="modal-header"><div><span class="eyebrow">RÜCKMELDUNG</span><h2>Was sollte geändert werden?</h2></div><button class="icon-button" data-close aria-label="Schließen">✕</button></header><form id="reject-form" class="modal-body">${textarea('Rückmeldung an die Redaktion','note','',5,'required maxlength="2000"')}<button class="button primary" type="submit">Mit Rückmeldung zurückgeben</button></form>`);dialog.className='';dialog.oncancel=null;
    bindAsync(dialog.querySelector('#reject-form'),'submit',async event=>{event.preventDefault();const note=new FormData(event.target as HTMLFormElement).get('note');await api(`/api/admin/content/${item.id}/reject`,json('POST',{expected_revision:item.revision,note}));dialog.close();toast('Inhalt zur Überarbeitung zurückgegeben.');refresh();});
  }));
}
export async function inboxView(container:HTMLElement,user:User,refresh:()=>void,offset=0):Promise<void>{
  const batch=await api<Inquiry[]>('/api/admin/inquiries?limit=25&offset='+offset);const items=batch.slice(0,24);
  container.innerHTML=header('KONTAKT / STUDIO-POSTFACH','Hier beginnen neue Projekte.','Anfragen lesen, zuordnen und ihren Bearbeitungsstand pflegen.')+
    '<div class="notice">Anfragen werden in der lokalen Datenbank gespeichert. Ein automatischer E-Mail-Versand ist nicht eingerichtet. Löschen entfernt eine Anfrage aus der aktiven Datenbank; vorhandene Backups sind separat zu behandeln.</div>'+
    (items.length?`<div class="inquiry-list">${items.map(item=>`<details class="inquiry-card"><summary><span class="inquiry-avatar">${e(item.name.slice(0,1).toUpperCase())}</span><span class="inquiry-title"><strong>${e(item.name)}</strong><small>${e(item.service)} · ${date(item.created_at)}</small></span><span class="badge badge-${item.status==='new'?'pending':'draft'}">${({new:'Neu',in_progress:'In Bearbeitung',done:'Erledigt',spam:'Spam'} as Record<string,string>)[item.status]}</span><span>＋</span></summary><div class="inquiry-body"><p class="inquiry-message">${e(item.message)}</p><div class="inquiry-bottom"><a class="button" href="mailto:${encodeURIComponent(item.email)}">${e(item.email)} ↗</a>${select('Bearbeitungsstand','status',item.status,[['new','Neu'],['in_progress','In Bearbeitung'],['done','Erledigt'],['spam','Spam']],`data-inquiry="${item.id}"`)}${user.role==='admin'?`<button class="button danger-text" data-delete-inquiry="${item.id}">Löschen</button>`:''}</div></div></details>`).join('')}</div>`:'<div class="panel empty-state"><span class="empty-icon">'+icon('inbox')+'</span><h2>Noch keine Anfragen.</h2><p>Teste das Kontaktformular. Deine Nachricht erscheint danach hier.</p><a href="/kontakt" target="_blank" rel="noopener" class="button">Kontaktformular öffnen ↗</a></div>');
  addPaging(container,offset,24,batch.length>24,n=>void inboxView(container,user,refresh,n));
  container.querySelectorAll<HTMLSelectElement>('[data-inquiry]').forEach(input=>bindAsync(input,'change',async()=>{await api(`/api/admin/inquiries/${input.dataset.inquiry}`,json('PATCH',{status:input.value}));toast('Bearbeitungsstand gespeichert.');refresh();}));
  container.querySelectorAll<HTMLButtonElement>('[data-delete-inquiry]').forEach(button=>bindAsync(button,'click',async()=>{if(confirm('Diese Anfrage endgültig aus der aktiven Datenbank löschen?')){await api(`/api/admin/inquiries/${button.dataset.deleteInquiry}`,{method:'DELETE'});toast('Anfrage gelöscht.');refresh();}}));
}
export async function mediaView(container:HTMLElement,user:User,refresh:()=>void,offset=0):Promise<void>{
  const batch=await api<Media[]>('/api/admin/media?limit=25&offset='+offset);const media=batch.slice(0,24);
  const catalog=await getCatalog();
  container.innerHTML=header('BIBLIOTHEK / MEDIEN','Platz für deine Bilder.','Eigene Bilder und zwölf integrierte Standardgrafiken – lokal, wiederverwendbar und ohne externen Assetdienst.')+
    `<div class="notice">Medien sind nach dem Upload öffentlich abrufbar. Keine vertraulichen Dokumente hochladen. Erlaubt: JPG, PNG und WebP, maximal 8 MB / 20 Megapixel. Bilder werden neu als WebP gespeichert und auf höchstens 2.400 Pixel Kantenlänge begrenzt.</div>${user.role!=='moderator'?`<form id="upload-form" class="panel upload-panel"><div class="upload-heading">${icon('media')}<div><h2>Ein neues Bild</h2><p>Danach im Inhalt unter „Eigenes Titelbild“ auswählen.</p></div></div><div class="field-grid">${field('Bild auswählen','file','','file','required accept="image/png,image/jpeg,image/webp"')}${field('Alternativtext / Bildbeschreibung','alt','','text','required minlength="3" maxlength="200" placeholder="Was ist auf dem Bild zu sehen?"')}</div><button class="button primary" type="submit">Bild hochladen ↑</button></form>`:''}`+
    (media.length?`<div class="media-grid">${media.map(item=>`<figure class="media-card"><img src="/media/${item.id}" alt="${e(item.alt)}" loading="lazy"><figcaption><strong>${e(item.alt)}</strong><span>${item.width} × ${item.height} px · WebP</span></figcaption></figure>`).join('')}</div>`:'<div class="panel empty-state compact">Noch keine Bilder. Die Website verwendet aktuell ihre integrierten Grafikvorlagen.</div>');
  addPaging(container,offset,24,batch.length>24,n=>void mediaView(container,user,refresh,n));
  const library=document.createElement('section');library.className='asset-library';
  library.innerHTML=`<div class="panel-heading"><div><span class="eyebrow">INTEGRIERT / STANDARD-ASSETS</span><h2>Zwölf Formen. Viele Möglichkeiten.</h2></div>${helpButton('art')}</div><p class="field-hint">In Leistungen, Projekten und passenden Seitenmodulen unter „Standardgrafik“ auswählen. Hochgeladene Bilder haben Vorrang.</p><div class="asset-grid">${catalog.assets.map(asset=>`<article class="standard-asset"><img src="${e(asset.url)}" alt="${e(asset.name)} – Standardgrafik" loading="lazy"><div class="asset-meta"><h3>${e(asset.name)}</h3><p>${e(asset.category)} · SVG</p><div><a class="button small" href="${e(asset.url)}" download>SVG ↓</a>${user.role!=='moderator'?`<button type="button" class="button small" data-asset="${e(asset.id)}">Verwenden ↗</button>`:''}</div></div></article>`).join('')}</div>`;
  container.append(library);
  library.querySelectorAll<HTMLButtonElement>('[data-asset]').forEach(button=>bindAsync(button,'click',()=>openEditor(null,'service',user,refresh,{art:button.dataset.asset})));
  bindAsync(container.querySelector('#upload-form'),'submit',async event=>{
    event.preventDefault();const form=event.target as HTMLFormElement;const button=form.querySelector<HTMLButtonElement>('button[type=submit]')!;const body=new FormData(form);
    const file=body.get('file') as File;if(file.size>8*1024*1024){toast('Das Bild ist größer als 8 MB.',true);return;}
    button.disabled=true;try{await api('/api/admin/media',{method:'POST',body});toast('Bild hochgeladen.');refresh();}finally{button.disabled=false;}
  });
}
export async function teamView(container:HTMLElement,user:User,refresh:()=>void):Promise<void>{
  const users=await api<User[]>('/api/admin/users');
  container.innerHTML=header('WORKSPACE / TEAM','Klare Rollen. Gemeinsam arbeiten.','Administratoren verwalten das System. Die Redaktion erstellt Inhalte. Moderatoren prüfen und bearbeiten Anfragen.','<button class="button primary" id="add-user">＋ Zugang erstellen</button>')+
    `<div class="role-grid"><div class="panel"><h3>Administration</h3><p>Inhalte, Freigaben, Team, Einstellungen und alle Anfragen.</p></div><div class="panel"><h3>Redaktion</h3><p>Entwürfe, Seitenmodule und Medien. Kein Veröffentlichen, keine Anfragen.</p></div><div class="panel"><h3>Moderation</h3><p>Eingereichte Inhalte freigeben oder zurückgeben. Anfragen bearbeiten.</p></div></div><div class="panel table-wrap"><table><thead><tr><th>Teammitglied</th><th>Rolle</th><th>Status</th><th>Aktion</th></tr></thead><tbody>${users.map(member=>`<tr><td><strong>${e(member.name)}</strong><small>${e(member.email)}</small></td><td>${({admin:'Administration',editor:'Redaktion',moderator:'Moderation'})[member.role]}</td><td>${member.active?'Aktiv':'Deaktiviert'}</td><td>${member.id===user.id?'<span class="badge">Dein Konto</span>':`<button class="button small" data-user="${member.id}" data-active="${member.active?'0':'1'}">${member.active?'Deaktivieren':'Aktivieren'}</button>`}</td></tr>`).join('')}</tbody></table></div>`;
  container.querySelector('#add-user')!.addEventListener('click',()=>{
    const dialog=modal(`<header class="modal-header"><div><span class="eyebrow">TEAM</span><h2>Neuen Zugang erstellen</h2></div><button class="icon-button" data-close aria-label="Schließen">✕</button></header><form class="modal-body" id="user-form">${field('Name','name','','text','required minlength="2" maxlength="80"')}${field('E-Mail-Adresse','email','','email','required')}${field('Passwort (mindestens 12 Zeichen)','password','','password','required minlength="12" maxlength="256" autocomplete="new-password"')}${select('Rolle','role','editor',[['editor','Redaktion'],['moderator','Moderation'],['admin','Administration']])}<p class="field-hint">Keine automatische Einladungs-E-Mail. Zugangsdaten über einen geeigneten sicheren Kanal weitergeben.</p><button class="button primary">Zugang erstellen</button></form>`);dialog.className='';dialog.oncancel=null;
    bindAsync(dialog.querySelector('#user-form'),'submit',async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target as HTMLFormElement));await api('/api/admin/users',json('POST',data));dialog.close();toast('Teamzugang erstellt.');refresh();});
  });
  container.querySelectorAll<HTMLButtonElement>('[data-user]').forEach(button=>bindAsync(button,'click',async()=>{
    if(button.dataset.active==='0'&&!confirm('Diesen Zugang deaktivieren und alle Sitzungen beenden?'))return;
    await api('/api/admin/users/'+button.dataset.user,json('PATCH',{active:button.dataset.active==='1'}));toast('Zugang aktualisiert.');refresh();
  }));
}
export async function activityView(container:HTMLElement):Promise<void>{
  const entries=await api<{id:number;action:string;target:string;created_at:number;name:string|null}[]>('/api/admin/audit');
  container.innerHTML=header('WORKSPACE / AKTIVITÄT','Was hat sich verändert?','Die letzten 100 protokollierten Adminaktionen. Inhaltsversionen bleiben separat erhalten.')+
    `<div class="panel table-wrap"><table><thead><tr><th>Aktion</th><th>Person</th><th>Ziel-ID</th><th>Zeitpunkt</th></tr></thead><tbody>${entries.map(entry=>`<tr><td><strong>${e(({created:'Inhalt angelegt',save:'Entwurf gespeichert',publish:'Veröffentlicht',submit:'Zur Prüfung eingereicht',reject:'Zurückgegeben',restore:'Version wiederhergestellt',archive:'Archiviert',setup:'Ersteinrichtung',media_uploaded:'Bild hochgeladen',user_created:'Zugang erstellt',unpublish:'Offline genommen'} as Record<string,string>)[entry.action]||entry.action)}</strong></td><td>${e(entry.name||'Demo-System')}</td><td><code>${e(entry.target.slice(0,12))}</code></td><td class="muted">${date(entry.created_at)}</td></tr>`).join('')}</tbody></table></div>`;
}

export async function libraryView(container:HTMLElement,user:User,refresh:()=>void):Promise<void>{
 const catalog=await getCatalog();
 container.innerHTML=header('BAUKASTEN / BIBLIOTHEK','Ein System. Viele Möglichkeiten.','Vorlagen beginnen eine neue Seite. Eigene Bausteine speicherst du direkt im Modul-Editor.')+`<div class="notice">${catalog.modules.length} Modultypen · ${catalog.templates.length} Seitenvorlagen · ${catalog.assets.length} Standardgrafiken. Eingefügte Vorlagen sind unabhängige Kopien und bleiben vollständig bearbeitbar.</div><div class="library-page-grid">${catalog.templates.map(t=>`<article class="library-card template-card"><div class="template-stack">${t.blocks.slice(0,4).map(b=>miniModule(b.type)).join('')}</div><span class="eyebrow">${t.blocks.length} VORBEREITETE MODULE</span><h3>${e(t.name)}</h3><p>${e(t.description)}</p>${user.role!=='moderator'?`<button type="button" class="button primary" data-start-template="${e(t.id)}">Neue Seite damit beginnen ↗</button>`:''}</article>`).join('')}</div><div class="panel-heading section-space"><h2>Der Modulkatalog</h2>${helpButton('templates')}</div><div class="library-grid">${catalog.modules.map(m=>`<article class="library-card">${miniModule(m.type)}<div class="library-card-title"><span class="eyebrow">${e(m.category)}</span>${helpButton('module:'+m.type)}</div><h3>${e(m.name)}</h3><p>${e(m.description)}</p></article>`).join('')}</div>`;
 container.querySelectorAll<HTMLButtonElement>('[data-start-template]').forEach(button=>bindAsync(button,'click',()=>{const template=catalog.templates.find(t=>t.id===button.dataset.startTemplate)!;return openEditor(null,'page',user,refresh,{blocks:template.blocks.map(cloneBlock)});}));
}

function addPaging(container:HTMLElement,offset:number,size:number,more:boolean,load:(offset:number)=>void):void{
 if(offset===0&&!more)return;
 const nav=document.createElement('nav');nav.className='list-pagination';nav.setAttribute('aria-label','Weitere Einträge');
 nav.innerHTML=`<button class="button" type="button" data-page-prev ${offset===0?'disabled':''}>← Zurück</button><span>Seite ${Math.floor(offset/size)+1} · bis zu ${size} Einträge pro Ansicht</span><button class="button" type="button" data-page-next ${!more?'disabled':''}>Weiter →</button>`;
 nav.querySelector('[data-page-prev]')!.addEventListener('click',()=>load(Math.max(0,offset-size)));nav.querySelector('[data-page-next]')!.addEventListener('click',()=>load(offset+size));container.append(nav);
}
